modLoader="javafml"
loaderVersion="[45,)"
license="LGPL v3"
issueTrackerURL="https://github.com/GoryMoon/Chargers/issues"

[[mods]]
    modId="chargers"
    version="${file.jarVersion}"
    displayName="Chargers"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/chargers"
    authors="Gory_Moon"
    itemIcon="chargers:charger_t1"
    description='''
A mod that adds item charger blocks in tiers and a wireless one'''

[[dependencies.chargers]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chargers]]
    modId="curios"
    mandatory=false
    versionRange="[1.19.4-5.1.5.3,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.chargers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"