modLoader="javafml"
loaderVersion="[39,)"
license="LGPLv3"
issueTrackerURL="https://github.com/GoryMoon/Chargers/issues"

[[mods]]
    modId="chargers"
    version="${file.jarVersion}"
    displayName="Chargers"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/chargers"
    authors="Gory_Moon"
    description='''
A mod that adds item charger blocks in tiers and a wireless one
'''

[[dependencies.chargers]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chargers]]
    modId="curios"
    mandatory=false
    versionRange="[1.18.1-5.0.4.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.chargers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"