modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/GoryMoon/Chargers/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/chargers"
itemIcon = "chargers:charger_t1"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "curios"
type = "optional"
versionRange = "${curios_version_range}"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "brandonscore"
type = "optional"
versionRange = "$(bc_version_range)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "fluxnetworks"
type = "optional"
versionRange = "${flux_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "industrialforegoing"
type = "optional"
versionRange = "${if_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"